/**
 * 查询
 */
export const SET_NETWORKLIST = 'SET_NETWORKLIST' //管网查询list
export const SET_SEARCHPARAMS = 'SET_SEARCHPARAMS' //管网查询params
export const SET_ISSHOWSEARCHDETAIL = 'SET_ISSHOWSEARCHDETAIL'//查询详情展示
export const SET_DETAILVALUES = 'SET_DETAILVALUES'//详情信息
export const SET_EQUIPMENTLIST = 'SET_EQUIPMENTLIST'//设备查询list
export const SET_EQUIPMENTPARAMS = 'SET_EQUIPMENTPARAMS'//设备查询params
export const SET_EQUIPMENTDETAIL = 'SET_EQUIPMENTDETAIL'//设备详情
export const SET_ISSHOWEQUIPMENTDETAIL = 'SET_ISSHOWEQUIPMENTDETAIL'//设备查询展示
export const SET_FACTORYSEARCHLIST = 'SET_FACTORYSEARCHLIST'//厂站查询列表

/**
 * 统计
 */
export const SET_NETWORKRADIO = 'SET_NETWORKRADIO' //管网统计radio
export const SET_NETWORKRESULT = 'SET_NETWORKRESULT' //管网统计结果
export const SET_SEARCHLIST = 'SET_SEARCHLIST'//设备统计结果
/**
 * 分析
 */
export const SET_CONNECTLIST = 'SET_CONNECTLIST' //连通性分析list
export const SET_CONNECTDETAIL = 'SET_CONNECTDETAIL' //连通性分析detail
export const SET_ISSHOWCONNECT = 'SET_ISSHOWCONNECT'//连通性详情展示
export const SET_VALVEDETAIL = 'SET_VALVEDETAIL'//阀门详情
export const SET_ISSHOWVALVE = 'SET_ISSHOWVALVE'//阀门详情展示

/**
 * 维修
 */
export const SET_REPAIRDETAIL = 'SET_REPAIRDETAIL' //维修查询详情
export const SET_ISSHOWREPAIR = 'SET_ISSHOWREPAIR' //维修查询详情展示
export const SET_REPAIRSEARCHLIST = 'SET_REPAIRSEARCHLIST' //维修查询列表
export const SET_ISSHOWEDITREPAIR = 'SET_ISSHOWEDITREPAIR' //是否展示登记编辑
export const SET_REPAIREDITDETAIL = 'SET_REPAIREDITDETAIL' //编辑详情

// RepairEditDetail
/**
 * 实时
 */
export const SET_EQUIMENTTYPE = 'SET_EQUIMENTTYPE' //类型
export const SET_GEOMETRYSTR = 'SET_GEOMETRYSTR' //空间
export const SET_REALTIMEINDEX = 'SET_REALTIMEINDEX' //实时数据类型
export const SET_REALTIMRDETAIL = 'SET_REALTIMRDETAIL' //实时数据详情
export const SET_ISSHOWREALTIMEDETAIL = 'SET_ISSHOWREALTIMEDETAIL' //分布点详情弹窗展示
export const SET_ISOPENTIMER = 'SET_ISOPENTIMER'//是否开启定时器

/** 
 *地图
 */ 
export const SET_CLICKRESULT = 'SET_CLICKRESULT' //点击数据
export const SET_ISSHOWCLICKDETAIL = 'SET_ISSHOWCLICKDETAIL' //是否展示点击详情
export const SET_ISMEASURE = 'SET_ISMEASURE' //是否在测量
export const SET_MAPBASE = 'SET_MAPBASE' //设置全局mapBase


/**
 * 用户管理
 */
export const SET_USRQUERYLIST = 'SET_USRQUERYLIST' //用户查询
export const SET_USERQUERYDETAIL = 'SET_USERQUERYDETAIL' //用户详情
export const SET_ISSHOWUSERQUERYDETAIL = 'SET_ISSHOWUSERQUERYDETAIL' //用户详情展示
export const SET_COMSUPTIONLIST = 'SET_COMSUPTIONLIST' //用水量查询列表
export const SET_COMSUPTIONDETAIL = 'SET_COMSUPTIONDETAIL' //用水量查询详情
export const SET_ISSHOWCOMSUPTION = 'SET_ISSHOWCOMSUPTION' //用水量查询详情弹窗

/**
 * 巡查管理
 */
export const SET_ISSHOWFAULTLEVEL = 'SET_ISSHOWFAULTLEVEL'//故障等级展示
export const SET_ISSHOWFAULTDETAIL = 'SET_ISSHOWFAULTDETAIL'//故障详情展示
export const SET_FAULTDETAILVALUE = 'SET_FAULTDETAILVALUE'//故障详情内容
export const SET_BIGIMAGEURL = 'SET_BIGIMAGEURL' //大图片地址
export const SET_ISSHOWBIGIMAGE = 'SET_ISSHOWBIGIMAGE' //是否展示大图片